name: Release 2.0

on:
  workflow_run:
    workflows: ["Run Tests"]
#     branches: [development]
    types: 
      - completed

jobs:
  test:
    name: Test
    runs-on: linux
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go




